version: '3'

networks:
  novo-network:

services:
  # Databases
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db_jeeves
      - MYSQL_USER=db_user_jeeves
      - MYSQL_PASSWORD=chahcieYishi1wuu
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - novo-network
    ports:
      - "3306:3306"
    expose:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    networks:
      - novo-network
    ports:
      - "6379:6379"
    expose:
      - "6379:6379"

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - novo-network
    ports:
      - "11434:11434"
    expose:
      - "11434:11434"

volumes:
  my-db:

