services:
  # Database initialization container
  db-init:
    build: .
    container_name: sensemaker-db-init
    environment:
      NODE_ENV: production
      SQL_DB_HOST: db
      SQL_DB_CRED: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
      REDIS_CRED: null
    depends_on:
      - db
      - redis
    command: >
      bash -c "
        echo 'Waiting for database to be ready...'
        while ! nc -z db 3306; do sleep 1; done
        echo 'Running database migrations...'
        npm run migrate:database
        echo 'Database initialization complete!'
      "
    restart: "no"  # Don't restart this container

  app:
    extends:
      file: docker-compose.yml
      service: app
    depends_on:
      db-init:
        condition: service_completed_successfully
      db:
        condition: service_started
      redis:
        condition: service_started