//MARKDOWN ALLOWED
const faqOptions = [
  {
    id: 1,
    title: "What can I do with Novo?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. <br>Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  },
  {
    id: 2,
    title: "What is a Matter?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  }, {
    id: 3,
    title: "What cases can I find in Novo?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  }, {
    id: 4,
    title: "What can I do with Novo?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  },
  {
    id: 5,
    title: "What can I do with Novo?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. <br>Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  },
  {
    id: 6,
    title: "What is a Matter?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  }, {
    id: 7,
    title: "What cases can I find in Novo?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  }, {
    id: 8,
    title: "What can I do with Novo?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  },
  {
    id: 9,
    title: "What is a Matter?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  }, {
    id: 10,
    title: "What cases can I find in Novo?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  }, {
    id: 11,
    title: "What can I do with Novo?",
    content:
      '<br>**Lorem ipsum dolor sit amet, consectetur adipiscing elit.**<br>Proin iaculis sed quam eu vestibulum. Morbi hendrerit dolor at commodo lacinia. Aliquam erat volutpat. Phasellus mauris ante, sagittis eu pellentesque vitae, interdum eu tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br>Vestibulum felis nisl, interdum sit amet faucibus nec, scelerisque et felis. Vivamus vel elit consectetur, placerat massa hendrerit, aliquet ante. <br>Fusce vel rhoncus nisi. Praesent semper turpis sit amet quam fermentum hendrerit. Ut pellentesque luctus libero, vel maximus erat egestas ut.      Mauris et purus eu orci luctus hendrerit id a dolor. Nunc consequat ipsum nec odio convallis, laoreet ullamcorper velit sagittis. Curabitur sit amet massa convallis, tempor nisl eu, commodo dui. Morbi orci elit, suscipit sit amet sodales eget, consectetur vel urna. Phasellus a ornare mi. Suspendisse sollicitudin gravida tortor, nec sagittis felis tempus vel. In molestie odio sit amet aliquam iaculis. Cras condimentum nulla a accumsan egestas. Nullam dignissim nunc lectus, nec scelerisque risus eleifend eu. Vestibulum dignissim ligula eu purus imperdiet, tincidunt tempor magna aliquam. Maecenas convallis enim ut gravida venenatis. Vestibulum vitae nibh quis dui hendrerit posuere. Vivamus posuere lacinia laoreet.',
  },
];

export { faqOptions };
